# -*- coding: utf-8 -*-
"""Google Cloud Function TEST Script

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gPbfZl5gRoinH_aG1hHcnXi1JDsUguz1
"""



"""# Introduction

this test script will push a test text to Google Sheets every 1 second and after 10 times it will clear the sheet and start over. This is used to see if the Google Cloud Function will run continously.
"""



!pip install --upgrade -q gspread

from google.colab import auth
auth.authenticate_user()
import time

import gspread
from oauth2client.client import GoogleCredentials

gc = gspread.authorize(GoogleCredentials.get_application_default())

def clear_worksheet(ws):

  cell_list = ws.range("A1:C100")
  for cell in cell_list:
    cell.value = ''
  ws.update_cells(cell_list)

def updateSheet(cnt):
  # sh = gc.create('A new spreadsheet')
  test_text = f"This is a Test: {cnt}"
  # Open our new sheet and add some data.
  worksheet = gc.open('GCP - Cloud Function TEST Sheet').sheet1

  worksheet.update_acell(f'A{cnt+1}', test_text)

  # Go to https://sheets.google.com to see your new spreadsheet.

def run():
  cnt = 0
  totCnt = 0
  while True:
    cnt = cnt+1
    if cnt%10==0:
      worksheet = gc.open('GCP - Cloud Function TEST Sheet').sheet1
      clear_worksheet(worksheet)
      totCnt += 1 
      worksheet.update_acell("C5", f"total loops: {totCnt}")
      cnt=0
    # print(cnt)
    updateSheet(cnt)
    
    
    time.sleep(1)





